"""Write a Triton model repository that serves FlashJet.

    python -m flashjet.serving.model_repository /path/to/models [--name flashjet]
        [--backend auto|gpu|native|numpy] [--max-batch-size 64]

creates ``/path/to/models/<name>/{config.pbtxt,1/model.py}``, which
``tritonserver --model-repository=/path/to/models`` can load.  FlashJet itself
must be importable inside the server (install it there, or set PYTHONPATH).
"""

import argparse
import os

CONFIG = """name: "{name}"
backend: "python"
max_batch_size: {max_batch_size}
input [
  {{
    name: "p4"
    data_type: TYPE_FP64
    dims: [ -1, 4 ]
    allow_ragged_batch: true
  }},
  {{
    name: "algo"
    data_type: TYPE_FP64
    dims: [ 2 ]
  }}
]
output [
  {{
    name: "jet_idx"
    data_type: TYPE_INT32
    dims: [ -1 ]
  }},
  {{
    name: "n_jets"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }}
]
dynamic_batching {{
  max_queue_delay_microseconds: {queue_delay}
}}
instance_group [
  {{
    count: 1
    kind: {kind}
  }}
]
parameters: {{
  key: "backend"
  value: {{ string_value: "{backend}" }}
}}
"""

MODEL = '''"""Generated by flashjet.serving.model_repository; edit the package, not this."""

from flashjet.serving.triton_model import TritonPythonModel  # noqa: F401
'''


def write(directory, name="flashjet", backend="auto", max_batch_size=64, queue_delay=500, kind="KIND_CPU"):
    """Write the model directory and return its path."""
    model_dir = os.path.join(directory, name)
    os.makedirs(os.path.join(model_dir, "1"), exist_ok=True)
    with open(os.path.join(model_dir, "config.pbtxt"), "w") as f:
        f.write(
            CONFIG.format(
                name=name, backend=backend, max_batch_size=max_batch_size, queue_delay=queue_delay, kind=kind
            )
        )
    with open(os.path.join(model_dir, "1", "model.py"), "w") as f:
        f.write(MODEL)
    return model_dir


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("directory", help="model repository to write into")
    parser.add_argument("--name", default="flashjet")
    parser.add_argument("--backend", default="auto", choices=["auto", "gpu", "native", "numpy"])
    parser.add_argument("--max-batch-size", type=int, default=64)
    parser.add_argument("--queue-delay", type=int, default=500, help="dynamic batching delay in microseconds")
    parser.add_argument("--kind", default="KIND_CPU", help="instance kind (the GPU backend uses torch's device)")
    args = parser.parse_args(argv)
    print(write(args.directory, args.name, args.backend, args.max_batch_size, args.queue_delay, args.kind))


if __name__ == "__main__":
    main()
